---
driver:
  name: ec2
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  security_group_ids: ["travis-ci"]
  instance_type: c3.8xlarge

platforms:
  - name: centos-6.4
  - name: ubuntu-14.04
    driver:
      image_id: ami-d85e75b0

transport:
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  connection_timeout: 30
  connection_retries: 10
